feature_to_name_IoT = {
    'Source IP': 'Src IP',
    'Source Port': 'Src Port',
    'Destination IP': 'Dst IP',
    'Destination Port': 'Dst Port',
    'amount_Fwd': 'Tot Fwd Pkts',
    'amount_Bwd': 'Tot Bwd Pkts',
    'length_Fwd': 'TotLen Fwd Pkts',
    'length_Bwd': 'TotLen Bwd Pkts',
    'min_packet_length_Fwd': 'Fwd Pkt Len Min',
    'min_packet_length_Bwd': 'Bwd Pkt Len Min',
    'max_packet_length_Fwd': 'Fwd Pkt Len Max',
    'max_packet_length_Bwd': 'Bwd Pkt Len Max',
    'Timestamp': 'Timestamp',
    'FIN': 'FIN Flag Cnt', 
    'SYN': 'SYN Flag Cnt',
    'RST': 'RST Flag Cnt',
    'PSH': 'PSH Flag Cnt',
    'ACK': 'ACK Flag Cnt',
    'URG': 'URG Flag Cnt',
    'Protocol': 'Protocol',
    'TCP': '6',
    'Label': 'Label',
    'Attack Label': '1',
}

feature_to_name_CIC_2017 = {
    'Source IP': ' Source IP',
    'Source Port': ' Source Port',
    'Destination IP': ' Destination IP',
    'Destination Port': ' Destination Port',
    'amount_Fwd': ' Total Fwd Packets',
    'amount_Bwd': ' Total Backward Packets',
    'length_Fwd': ' Total Length of Bwd Packets',
    'length_Bwd': ' Total Length of Bwd Packets',
    'min_packet_length_Fwd': ' Fwd Packet Length Min',
    'min_packet_length_Bwd': ' Bwd Packet Length Min',
    'max_packet_length_Fwd': ' Fwd Packet Length Max',
    'max_packet_length_Bwd': 'Bwd Packet Length Max',
    'Timestamp': ' Timestamp',
    'FIN': 'FIN Flag Count', 
    'SYN': ' SYN Flag Count',
    'RST': ' RST Flag Count',
    'PSH': ' PSH Flag Count',
    'ACK': ' ACK Flag Count',
    'URG': ' URG Flag Count',
    'Protocol': ' Protocol',
    'TCP': '6',
}

feature_to_name_elastic = {
    'Source IP': 'Source_IP',
    'Source Port': 'Source_port',
    'Destination IP': 'Destination_IP',
    'Destination Port': 'Destination_port',
    'amount_Fwd': 'fwd_packets_amount',
    'amount_Bwd': 'bwd_packets_amount',
    'length_Fwd': 'fwd_packets_length',
    'length_Bwd': 'bwd_packets_length',
    'min_packet_length_Fwd': 'min_fwd_packet',
    'min_packet_length_Bwd': 'min_bwd_packet',
    'max_packet_length_Fwd': 'max_fwd_packet ',
    'max_packet_length_Bwd': 'max_bwd_packet',
    'Timestamp': 'Timestamp',
    'FIN': 'FIN_count', 
    'SYN': 'SYN_count',
    'RST': 'RST_count',
    'PSH': 'PSH_count',
    'ACK': 'PSH_count',
    'URG': 'URG_count',
    'Protocol': 'Protocol',
    'TCP': 'tcp',
    'Label': 'label',
    'Attack Label': 'malware',
}